exp09-web:
  image: cloudopting/exp09-web
  links:
    - exp09-app
  ports:
    - "80:80"
exp09-app:
  image: cloudopting/exp09-app
  links:
    - exp09-db
exp09-db:
  image: cloudopting/exp09-db
  volumes:
    - ~/exp09data:/var/lib/mysql

